"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import {
  Briefcase,
  Building2,
  CalendarDays,
  Eye,
  MessageSquareText,
  Send,
  X,
} from "lucide-react";
import { fetchMessages } from "@/lib/api/message";
import { ColdMessageRecord } from "@/types/application";
import SortIndicator from "@/components/ui/sort-indicator";
import HourglassLoader from "@/components/ui/hourglass-loader";
import DataRowCard from "@/components/ui/data-row-card";
import ViewModeToggle from "@/components/ui/view-mode-toggle";
import { useViewMode } from "@/hooks/use-view-mode";

type MessageSortKey = "company" | "role" | "message" | "updatedAt";

export default function MessagesPage() {
  const [messages, setMessages] = useState<ColdMessageRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [previewMessage, setPreviewMessage] = useState<string | null>(null);
  const [sortBy, setSortBy] = useState<MessageSortKey>("updatedAt");
  const [sortDir, setSortDir] = useState<"asc" | "desc">("desc");
  const { viewMode, setViewMode } = useViewMode("messages-view-mode");

  const sortIndicator = (key: MessageSortKey) => {
    return <SortIndicator active={sortBy === key} direction={sortDir} />;
  };

  useEffect(() => {
    async function loadMessages() {
      try {
        const data = await fetchMessages();
        setMessages(data);
      } catch {
        setError("Failed to load messages.");
      } finally {
        setLoading(false);
      }
    }

    loadMessages();
  }, []);

  const handleSort = (key: MessageSortKey) => {
    if (sortBy === key) {
      setSortDir((prev) => (prev === "asc" ? "desc" : "asc"));
      return;
    }
    setSortBy(key);
    setSortDir("asc");
  };

  const sortedMessages = useMemo(() => {
    const getValue = (message: ColdMessageRecord) => {
      if (sortBy === "company") return message.applicationId?.jobId?.jobCompany?.toLowerCase() ?? "";
      if (sortBy === "role") return message.applicationId?.jobId?.jobProfile?.toLowerCase() ?? "";
      if (sortBy === "message") return message.message.toLowerCase();
      return new Date(message.updatedAt).getTime();
    };

    return [...messages].sort((a, b) => {
      const aValue = getValue(a);
      const bValue = getValue(b);
      if (aValue === bValue) return 0;
      const result = aValue > bValue ? 1 : -1;
      return sortDir === "asc" ? result : -result;
    });
  }, [messages, sortBy, sortDir]);

  if (loading) {
    return <HourglassLoader label="Loading messages..." />;
  }

  if (error) {
    return <div className="p-6 text-sm text-red-600">{error}</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold">Messages</h1>
          <p className="mt-1 text-sm text-gray-500">Saved cold outreach messages generated by AI.</p>
        </div>
        <ViewModeToggle value={viewMode} onChange={setViewMode} />
      </div>

      {viewMode === "table" ? (
        <div className="overflow-x-auto rounded-2xl border border-white/45 bg-white/70 shadow-[0_16px_46px_rgba(76,48,160,0.14)] backdrop-blur-xl">
          {sortedMessages.length === 0 ? (
            <div className="p-6 text-sm text-gray-500">No messages found.</div>
          ) : (
            <table className="min-w-262.5 w-full text-sm">
              <thead className="bg-white/50 text-slate-600">
                <tr>
                  <th className="px-6 py-3 text-left">
                    <button className="inline-flex items-center gap-1 font-medium hover:underline" onClick={() => handleSort("company")}>
                      Company <span className="text-xs text-gray-500">{sortIndicator("company")}</span>
                    </button>
                  </th>
                  <th className="px-6 py-3 text-left">
                    <button className="inline-flex items-center gap-1 font-medium hover:underline" onClick={() => handleSort("role")}>
                      Role <span className="text-xs text-gray-500">{sortIndicator("role")}</span>
                    </button>
                  </th>
                  <th className="px-6 py-3 text-left">
                    <button className="inline-flex items-center gap-1 font-medium hover:underline" onClick={() => handleSort("message")}>
                      Message <span className="text-xs text-gray-500">{sortIndicator("message")}</span>
                    </button>
                  </th>
                  <th className="px-6 py-3 text-left">
                    <button className="inline-flex items-center gap-1 font-medium hover:underline" onClick={() => handleSort("updatedAt")}>
                      Updated <span className="text-xs text-gray-500">{sortIndicator("updatedAt")}</span>
                    </button>
                  </th>
                  <th className="px-6 py-3 text-left">Application</th>
                </tr>
              </thead>
              <tbody>
                {sortedMessages.map((item) => (
                  <tr key={item._id} className="border-t border-white/55 align-top transition hover:bg-white/55">
                    <td className="px-6 py-4 font-medium text-slate-900">
                      <span className="inline-flex items-center gap-2">
                        <Building2 className="h-4 w-4 text-indigo-500" />
                        {item.applicationId?.jobId?.jobCompany ?? "N/A"}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-slate-700">
                      <span className="inline-flex items-center gap-2">
                        <Briefcase className="h-4 w-4 text-blue-500" />
                        {item.applicationId?.jobId?.jobProfile ?? "N/A"}
                      </span>
                    </td>
                    <td className="max-w-64 px-6 py-4">
                      <p className="line-clamp-2 text-gray-700">
                        <span className="mr-2 inline-flex align-middle">
                          <MessageSquareText className="h-4 w-4 text-violet-500" />
                        </span>
                        {item.message}
                      </p>
                      <button
                        type="button"
                        onClick={() => setPreviewMessage(item.message)}
                        className="mt-2 inline-flex gap-0.5 items-center text-sm text-blue-700 cursor-pointer hover:text-blue-900 hover:underline"
                      >
                        <Eye className="h-3.5 w-3.5" /> View Full
                      </button>
                    </td>
                    <td className="px-6 py-4 text-gray-500">
                      <span className="inline-flex items-center gap-2">
                        <CalendarDays className="h-4 w-4 text-slate-400" />
                        {new Date(item.updatedAt).toLocaleDateString()}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      {item.applicationId?._id ? (
                        <Link href={`/applications/${item.applicationId._id}`} className="inline-flex items-center gap-0.5 text-blue-700 hover:text-blue-900 hover:underline">
                          <Send className="h-3.5 w-3.5" /> Open
                        </Link>
                      ) : (
                        <span className="text-gray-400">N/A</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      ) : (
        <div className="grid auto-rows-fr grid-cols-1 gap-4 p-4 sm:p-6 md:grid-cols-2 xl:grid-cols-3">
          {sortedMessages.map((item) => (
            <DataRowCard
              key={item._id}
              title={item.applicationId?.jobId?.jobCompany ?? "N/A"}
              subtitle={item.applicationId?.jobId?.jobProfile ?? "N/A"}
              icon={<Building2 className="h-4 w-4" />}
              fieldsColumns={1}
              className="h-full"
              fields={[
                {
                  label: "Message",
                  value: <p className="line-clamp-4">{item.message}</p>,
                },
                {
                  label: "Updated",
                  value: (
                    <span className="inline-flex items-center gap-2">
                      <CalendarDays className="h-4 w-4 text-slate-400" />
                      {new Date(item.updatedAt).toLocaleDateString()}
                    </span>
                  ),
                },
              ]}
              actions={
                <>
                  <button
                    type="button"
                    onClick={() => setPreviewMessage(item.message)}
                    className="text-sm text-blue-700 cursor-pointer inline-flex gap-0.5 items-center hover:text-blue-900 hover:underline"
                  >
                    <Eye className="h-3.5 w-3.5" /> View Full
                  </button>
                  {item.applicationId?._id ? (
                    <Link href={`/applications/${item.applicationId._id}`} className="inline-flex gap-0.5 items-center text-sm cursor-pointer text-blue-700 hover:text-blue-900 hover:underline">
                      <Send className="h-3.5 w-3.5" /> Open Application
                    </Link>
                  ) : null}
                </>
              }
            />
          ))}
        </div>
      )}
      {previewMessage ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
          <div className="w-full max-w-2xl rounded-xl bg-white shadow-xl">
            <div className="flex items-center justify-between border-b px-5 py-4">
              <h2 className="font-semibold">Message Preview</h2>
              <button
                type="button"
                onClick={() => setPreviewMessage(null)}
                className="rounded-full p-1 text-sm text-gray-500 cursor-pointer transition hover:bg-gray-700 hover:text-white"
              >
                <X />
              </button>
            </div>
            <div className="space-y-3 px-5 py-4 text-sm">
              <div>
                <p className="max-h-[50vh] overflow-y-auto whitespace-pre-wrap pr-1 text-gray-700">
                  {previewMessage}
                </p>
              </div>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}

