"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { fetchMessages } from "@/lib/api/message";
import { ColdMessageRecord } from "@/types/application";
import { X } from "lucide-react";
import SortIndicator from "@/components/ui/sort-indicator";
import HourglassLoader from "@/components/ui/hourglass-loader";

type MessageSortKey = "company" | "role" | "message" | "updatedAt";

export default function MessagesPage() {
  const [messages, setMessages] = useState<ColdMessageRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [previewMessage, setPreviewMessage] = useState<string | null>(null);
  const [sortBy, setSortBy] = useState<MessageSortKey>("updatedAt");
  const [sortDir, setSortDir] = useState<"asc" | "desc">("desc");

  const sortIndicator = (key: MessageSortKey) => {
    return <SortIndicator active={sortBy === key} direction={sortDir} />;
  };

  useEffect(() => {
    async function loadMessages() {
      try {
        const data = await fetchMessages();
        setMessages(data);
      } catch {
        setError("Failed to load messages.");
      } finally {
        setLoading(false);
      }
    }

    loadMessages();
  }, []);

  const handleSort = (key: MessageSortKey) => {
    if (sortBy === key) {
      setSortDir((prev) => (prev === "asc" ? "desc" : "asc"));
      return;
    }
    setSortBy(key);
    setSortDir("asc");
  };

  const sortedMessages = useMemo(() => {
    const getValue = (message: ColdMessageRecord) => {
      if (sortBy === "company") return message.applicationId?.jobId?.jobCompany?.toLowerCase() ?? "";
      if (sortBy === "role") return message.applicationId?.jobId?.jobProfile?.toLowerCase() ?? "";
      if (sortBy === "message") return message.message.toLowerCase();
      return new Date(message.updatedAt).getTime();
    };

    return [...messages].sort((a, b) => {
      const aValue = getValue(a);
      const bValue = getValue(b);
      if (aValue === bValue) return 0;
      const result = aValue > bValue ? 1 : -1;
      return sortDir === "asc" ? result : -result;
    });
  }, [messages, sortBy, sortDir]);

  if (loading) {
    return <HourglassLoader label="Loading messages..." />;
  }

  if (error) {
    return <div className="p-6 text-sm text-red-600">{error}</div>;
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold">Messages</h1>
        <p className="text-sm text-gray-500 mt-1">Saved cold outreach messages generated by AI.</p>
      </div>

      <div className="bg-white border rounded-xl shadow-sm overflow-x-auto">
        {sortedMessages.length === 0 ? (
          <div className="p-6 text-sm text-gray-500">No messages found.</div>
        ) : (
          <table className="w-full text-sm min-w-[1000px]">
            <thead className="bg-gray-50 text-gray-600">
              <tr>
                <th className="text-left px-6 py-3">
                  <button className="font-medium hover:underline inline-flex items-center gap-1" onClick={() => handleSort("company")}>
                    Company <span className="text-xs text-gray-500">{sortIndicator("company")}</span>
                  </button>
                </th>
                <th className="text-left px-6 py-3">
                  <button className="font-medium hover:underline inline-flex items-center gap-1" onClick={() => handleSort("role")}>
                    Role <span className="text-xs text-gray-500">{sortIndicator("role")}</span>
                  </button>
                </th>
                <th className="text-left px-6 py-3">
                  <button className="font-medium hover:underline inline-flex items-center gap-1" onClick={() => handleSort("message")}>
                    Message <span className="text-xs text-gray-500">{sortIndicator("message")}</span>
                  </button>
                </th>
                <th className="text-left px-6 py-3">
                  <button className="font-medium hover:underline inline-flex items-center gap-1" onClick={() => handleSort("updatedAt")}>
                    Updated <span className="text-xs text-gray-500">{sortIndicator("updatedAt")}</span>
                  </button>
                </th>
                <th className="text-left px-6 py-3">Application</th>
              </tr>
            </thead>
            <tbody>
              {sortedMessages.map((item) => (
                <tr key={item._id} className="border-t hover:bg-gray-50 align-top">
                  <td className="px-6 py-4 font-medium">{item.applicationId?.jobId?.jobCompany ?? "N/A"}</td>
                  <td className="px-6 py-4">{item.applicationId?.jobId?.jobProfile ?? "N/A"}</td>
                  <td className="px-6 py-4 max-w-64">
                    <p className="text-gray-700 line-clamp-2">{item.message}</p>
                    <button
                      type="button"
                      onClick={() => setPreviewMessage(item.message)}
                      className="mt-2 text-xs text-blue-600 hover:underline"
                    >
                      View full
                    </button>
                  </td>
                  <td className="px-6 py-4 text-gray-500">{new Date(item.updatedAt).toLocaleDateString()}</td>
                  <td className="px-6 py-4">
                    {item.applicationId?._id ? (
                      <Link href={`/applications/${item.applicationId._id}`} className="text-blue-600 hover:underline">
                        Open
                      </Link>
                    ) : (
                      <span className="text-gray-400">N/A</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
        {previewMessage ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
          <div className="w-full max-w-2xl rounded-xl bg-white shadow-xl">
            <div className="flex items-center justify-between border-b px-5 py-4">
              <h2 className="font-semibold">Message Preview</h2>
              <button
                type="button"
                onClick={() => setPreviewMessage(null)}
                className="text-sm text-gray-500 cursor-pointer hover:text-gray-700"
              >
                <X />
              </button>
            </div>
            <div className="space-y-3 px-5 py-4 text-sm">
              <div>
                <p className="whitespace-pre-wrap text-gray-700 max-h-[50vh] overflow-y-auto pr-1">
                  {previewMessage}
                </p>
              </div>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}


